!(comments added by hand)
!File generated by the -exports option of my M compiler.
!Creates an interface module suitable for using this library via a DLL
!Normally the library would just be imported like any other module, and be a static part of the program)

importlib bignum =
    type bignum = ref bignumrec
    record bignumrec = 
        ref [0:]i32 num
        i64 length
        i64 expon
        i32 neg
        i32 numtype
    end

    mlang proc     bn_print(bignum a,i64 format=0)
    mlang proc     bn_println(bignum a,i64 format=0)
    mlang function bn_alloc(i64 size) => ref void
    mlang proc     bn_free(bignum a)
    mlang proc     bn_setzero(bignum a)
    mlang proc     bn_move(bignum a,b)
    mlang proc     bn_dupl(bignum a,b)
    mlang proc     bn_setinf(bignum dest)
    mlang proc     bn_setnan(bignum dest)
    mlang function bn_iszero(bignum a) => i64
    mlang proc     bn_negto(bignum a)
    mlang proc     bn_absto(bignum a)
    mlang function bn_isint(bignum a) => i64
    mlang function bn_getprec(bignum a) => i64
    mlang proc     bn_setprec(bignum a,i64 prec)
    mlang function bn_getglobalprec() => i64
    mlang proc     bn_setglobalprec(i64 prec)
    mlang function bn_makeint(i64 x) => bignum
    mlang function bn_makefloat(r64 x) => bignum
    mlang proc     bn_ipower(bignum d,a,i64 n)
    mlang function bn_equal(bignum a,b) => i64
    mlang proc     bn_addu(bignum dest,a,b)
    mlang proc     bn_idivu(bignum dest,a,b,rm=nil)
    mlang function bn_makestr(ichar s,i64 length=0) => bignum
    mlang function bn_tostring(bignum a,i64 fmt=0) => ichar
    mlang function bn_add(bignum dest,a,b) => i64
    mlang function bn_sub(bignum dest,a,b) => i64
    mlang function bn_mul(bignum dest,a,b) => i64
    mlang function bn_mulp(bignum dest,a,b,i64 prec) => i64
    mlang function bn_div(bignum dest,a,b,i64 prec=0) => i64
    mlang function bn_idiv(bignum dest,a,b) => i64
    mlang function bn_idivrem(bignum dest,rm,a,b) => i64
    mlang function bn_irem(bignum dest,a,b) => i64
    mlang function bn_cmp(bignum a,b) => i64
    mlang function bn_const(i64 value) => bignum
    mlang function bn_sign(bignum a) => i64
    mlang function bn_digits(bignum a) => i64
    mlang function bn_toint(bignum a) => i64
    mlang function bn_tofloat(bignum a) => r64
    mlang proc     bn_fix(bignum c,a)
end importlib
